version: '3.9.10'
volumes:
  postgres_data:
  static_value:
  media_value:

services:
  postgres:
    image: postgres:15.2
    container_name: api_yamdb_db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    build: ./
    container_name: api_yamdb_web
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8080:8080'
    depends_on:
      - postgres
