# Generated by Django 3.2 on 2023-04-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Укажите биографию пользователей', verbose_name='Биография'),
        ),
    ]
