# Generated by Django 3.2 on 2023-04-27 08:04

import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('role', 'username'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Укажите категорию', max_length=255, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Текст комментария к отзывам', max_length=255, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Укажите жанр', max_length=255, unique=True, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(help_text='Укажите оценку от 1 до 10', validators=[django.core.validators.MinValueValidator(1, message='Минимальная оценка не может быть ниже: 1'), django.core.validators.MaxValueValidator(10, message='Максимальная оценка не может быть выше: 10')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(help_text='Введите текст отзыва', max_length=255, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='Добавьте название', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Укажите год выхода', validators=[reviews.validators.validate_year], verbose_name='Год выхода'),
        ),
    ]
